# Generated by Django 5.2.7 on 2025-10-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=10)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
